# Generated by Django 4.2.11 on 2024-03-30 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oauth_app', '0003_uploadedfile_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadedfile',
            name='additional_info',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='date_and_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='incident_type',
            field=models.CharField(blank=True, choices=[('option1', 'Hazing'), ('option2', 'Sexual Misconduct'), ('option3', 'Verbal Abuse'), ('option4', 'Physical Abuse'), ('option5', 'Substance Abuse'), ('option6', 'Discrimination'), ('other', 'Other')], max_length=200),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='injuries',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='organizations_involved',
            field=models.CharField(blank=True, choices=[('', '---------'), ('option1', 'None'), ('option2', 'Fraternity'), ('option3', 'Sorority'), ('option4', 'Academic Club'), ('option5', 'Non-Academic Club'), ('option6', 'Sports'), ('option7', 'Societies'), ('other', 'Other')], max_length=200),
        ),
        migrations.AddField(
            model_name='uploadedfile',
            name='who_was_involved',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
